import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GetStaticProps } from "next";

const Home = ({ pkmData }: any) => {
  
  console.log(pkmData);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {pkmData.map((pkm: { name: string; link: string }, i: string) => (
            <ul key={i}>{pkm.name}, {Number(i)+1}</ul>
          ))}
        </ul>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async (ctx) => {
  const res = await fetch("https://pokeapi.co/api/v2/pokemon?limit=151");
  const data = await res.json();

  return {
    props: {
      pkmData: data.results,
    },
  };
};

export default Home;
