import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { IPokemonData, IReceivedData } from "../interfaces/interfaces";
import Image from "next/image";

const Home = ({ pkmArray }: InferGetStaticPropsType<GetStaticProps>) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {pkmArray.map((pkm: IPokemonData, i: string) => (
          <div key={i}>
            <Image
              src={pkm.sprites.front_default}
              alt={`${pkm.name} image`}
              width={50}
              height={50}
            />
            <h2>{pkm.name}</h2>
          </div>
        ))}
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("https://pokeapi.co/api/v2/pokemon?limit=5");
  const pkmData: IReceivedData = await res.json();
  const pkmArray = await Promise.all(
    pkmData.results.map(async (data) => {
      const newRes = await fetch(data.url);
      const finalRes: IPokemonData = await newRes.json();
      return {
        name: finalRes.name,
        id: finalRes.id,
        sprites: {
          front_default: finalRes.sprites.front_default,
        },
      };
    })
  );

  return {
    props: {
      pkmArray,
    },
  };
};

export default Home;
